### PR TITLE
fix/UserLeaderboard

### PR DESCRIPTION
**Pull request by PLsergent**
Hi !

A little PR to fix something related to the `UserLeaderboard` class. I removed the `gamemode` from the method `MulpyVersus.get_user_leaderboard_in_gamemode()` parameters since it wasn't in the `__init__` parameters, we can then specify the gamemode in the method `UserLeaderboard.get_score_in_gamemode` as intended originally I guess :)

### CODE REVIEW

**Comment by PLsergent** [comment]
Now I see that I'm getting a 404! I think there is an issue with the API

**Comment by PLsergent** [comment]
Okay I found the issue ! All good !

**Review by AshladBP — APPROVED** [review]

**Comment by PLsergent** [comment]
Can you merge for me since I didn't use a sign commit ? @AshladBP

**Comment by AshladBP** [comment]
> Can you merge for me since I didn't use a sign commit ? @AshladBP 

Sure, done!

**Pull request merged**
